### ISSUE TITLE
Test suite broken with profiling on

### ISSUE THREAD

**Issue by shlevy** [hspec/HUnit#22] opened 2018-01-10 19:07 UTC
When building with profiling enabled, I get:

> ### Failure in: 1:2:error                     
> tests/HUnitTestBase.lhs:34
> for the reports from a test,
> expected: [Start (State {path = [], counts = Counts {cases = 1, tried = 0, errors = 0, failures = 0}}),Error "error\nCallStack (from HasCallStack):\n  error, called at tests/HUnitTestExtended.hs:11:13 in main:HUnitTestExtended" (State {path = [], counts = Counts {cases = 1, tried = 1, errors = 1, failures = 0}})]
>  but got: [Start (State {path = [], counts = Counts {cases = 1, tried = 0, errors = 0, failures = 0}}),Error "error\nCallStack (from HasCallStack):\n  error, called at tests/HUnitTestExtended.hs:11:13 in main:HUnitTestExtended\nCallStack (from -prof):\n  HUnitTestExtended.errorCall (tests/HUnitTestExtended.hs:11:1-25)\n  HUnitTestExtended.CAF (<entire-module>)" (State {path = [], counts = Counts {cases = 1, tried = 1, errors = 1, failures = 0}})]
>

**Comment by sol** [comment] 2018-01-10 19:27
Unless somebody opens a PR and the fix doesn't turn out to be too ugly, this is a "wontfix".

**Comment by sol** [comment] 2018-01-10 19:31
Closing, PRs still welcome.

**Closed by sol** 2018-01-10 19:31 UTC
Labels: wontfix

**Comment by Rotaerk** [comment] 2018-03-25 00:44
@sol,

I'm considering building a PR to resolve this problem.  The cause of the problem is here: https://github.com/hspec/HUnit/blob/2b20abcd6a79c9ad1313afcf18257b29f67f2acf/tests/HUnitTestExtended.hs#L27

A hard-coded error string is being compared to the result of serializing the exception thrown by `errorCall`, to test that `errorCall` produces the expected exception (although it's really for testing `expectError`).  This is a problem because, when profiling is enabled, the error message gets an additional stack trace, which you can see in the error reported by @shlevy:  `CallStack (from -prof):\n HUnitTestExtended.errorCall (tests/HUnitTestExtended.hs:11:1-25)\n HUnitTestExtended.CAF ()`.

I'm just not really sure what exactly the fix should be.  In version 4.9.0.0 of GHC, the `error` function (which is used by `errorCall`) was changed from displaying just the error message, to displaying the error message and a stack trace.  Hence this logic:  https://github.com/hspec/HUnit/blob/2b20abcd6a79c9ad1313afcf18257b29f67f2acf/tests/HUnitTestExtended.hs#L25-L31

A better way to implement line 27 would've been this:

`expectError "error" (TestCase (errorWithoutStackTrace "error"))`.

Unfortunately, that still doesn't solve the problem:  `errorWithoutStackTrace` actually still includes the profiling part of the stack trace, for some reason.  (I reported this as a [GHC bug](https://ghc.haskell.org/trac/ghc/ticket/14970), but I'm not sure if this actually unintended.)  So with profiling on, the `expectError` test _still_ fails.

In any case, I don't think this is a problem specific to HUnitTestExtended.hs.  Rather, it seems to be a fundamental problem with `expectError`, itself:  Anyone who builds a test case using `expectError` would likely face the same problem, because there would be no string they could hard-code that would reliably match the thrown exception.

What I'm thinking might be the correct fix is a pretty big change to HUnit.  Particularly, `performTestCase` shouldn't convert the error to a string here: https://github.com/hspec/HUnit/blob/691dd02c3137eed621ba042d62f35c3bb70e5b5d/src/Test/HUnit/Lang.hs#L104

Instead, the test cases should have access to the caught exception data structure itself.  You could then build a variant of `expectError` that tests the thrown exception without relying on serialization stability.
