### ISSUE TITLE
<<loop>> error?

### ISSUE THREAD

**Issue by chrissound** [hspec/HUnit#16] opened 2017-02-12 17:04 UTC
I'm getting the following output, I don't understand the error message.

Any ideas?
```
Cases: 1  Tried: 0  Errors: 0  Failures: 0render m
render m
### Error in:   0:test1                   
<<loop>>
Cases: 1  Tried: 1  Errors: 1  Failures: 0
Counts {cases = 1, tried = 1, errors = 1, failures = 0}
```

**Comment by sol** [comment] 2017-02-13 01:49
This is most likely not a bug in HUnit, but your test suite writing to stdout/stderr.

Please provide steps to reproduce, version used, etc. with bug reports.  Closing.

**Closed by sol** 2017-02-13 01:49 UTC

**Comment by chrissound** [comment] 2017-02-13 10:48
Thanks for the advice - it seems to be just an infinite loop causing the error.
